import type { WorkspaceData } from "./types";

export const demoData: WorkspaceData = {
  user: { name: "Carlos", email: "carlos@empresa.mx" },
  metaConnection: {
    status: "demo",
    userName: "Cuenta de demostración",
    connectedAt: "2026-08-14T16:30:00.000Z",
    lastSyncAt: "2026-09-03T19:36:00.000Z",
  },
  organizations: [
    {
      id: "org-casa-norte",
      name: "Casa Norte",
      initials: "CN",
      color: "#7c5cff",
      pageName: "Casa Norte México",
      instagramHandle: "@casanorte.mx",
      adAccountId: "act_1029384756",
      currency: "MXN",
      objective: "Ventas",
      mode: "autonomous",
      monthlyLimit: 80000,
      spentThisMonth: 42680,
      revenueThisMonth: 148920,
      resultValue: 1241,
      connected: true,
    },
    {
      id: "org-brava",
      name: "Brava Studio",
      initials: "BS",
      color: "#f97349",
      pageName: "Brava Studio",
      instagramHandle: "@brava.studio",
      adAccountId: "act_2837465019",
      currency: "MXN",
      objective: "Prospectos",
      mode: "copilot",
      monthlyLimit: 35000,
      spentThisMonth: 18750,
      revenueThisMonth: 56200,
      resultValue: 850,
      connected: true,
    },
    {
      id: "org-lumbre",
      name: "Lumbre Café",
      initials: "LC",
      color: "#13b981",
      pageName: "Lumbre Café MX",
      instagramHandle: "@lumbrecafe",
      adAccountId: "act_9182736450",
      currency: "MXN",
      objective: "Mensajes",
      mode: "observer",
      monthlyLimit: 22000,
      spentThisMonth: 9820,
      revenueThisMonth: 24800,
      resultValue: 310,
      connected: true,
    },
  ],
  campaigns: [
    {
      id: "cmp-1", organizationId: "org-casa-norte", name: "Prospección · Colección Otoño", status: "ACTIVE",
      objective: "Ventas", channel: "Facebook + Instagram", spend: 18420, results: 62, costPerResult: 297.1,
      revenue: 71360, roas: 3.87, trend: 18.4, dailyBudget: 1450, updatedAt: "Hace 12 min",
    },
    {
      id: "cmp-2", organizationId: "org-casa-norte", name: "Remarketing · 30 días", status: "ACTIVE",
      objective: "Ventas", channel: "Facebook + Instagram", spend: 12860, results: 54, costPerResult: 238.15,
      revenue: 52920, roas: 4.12, trend: 9.2, dailyBudget: 980, updatedAt: "Hace 18 min",
    },
    {
      id: "cmp-3", organizationId: "org-casa-norte", name: "Advantage+ · Catálogo", status: "ACTIVE",
      objective: "Ventas", channel: "Instagram", spend: 8370, results: 28, costPerResult: 298.93,
      revenue: 21840, roas: 2.61, trend: -6.8, dailyBudget: 720, updatedAt: "Hace 31 min",
    },
    {
      id: "cmp-4", organizationId: "org-casa-norte", name: "Prueba · Audiencia amplia", status: "PAUSED",
      objective: "Ventas", channel: "Facebook", spend: 3030, results: 6, costPerResult: 505,
      revenue: 8800, roas: 2.9, trend: -14.1, dailyBudget: 400, updatedAt: "Ayer",
    },
    {
      id: "cmp-5", organizationId: "org-brava", name: "Lead Gen · Dueños de negocio", status: "ACTIVE",
      objective: "Prospectos", channel: "Facebook + Instagram", spend: 11220, results: 74, costPerResult: 151.62,
      revenue: 38250, roas: 3.41, trend: 12.1, dailyBudget: 900, updatedAt: "Hace 22 min",
    },
    {
      id: "cmp-6", organizationId: "org-lumbre", name: "Mensajes · Zona Roma", status: "ACTIVE",
      objective: "Mensajes", channel: "Instagram", spend: 9820, results: 126, costPerResult: 77.94,
      revenue: 24800, roas: 2.53, trend: 5.7, dailyBudget: 560, updatedAt: "Hace 8 min",
    },
  ],
  ads: [
    { id: "ad-1a", organizationId: "org-casa-norte", campaignId: "cmp-1", adSetId: "as-1", name: "Otoño · Sala completa", status: "ACTIVE", spend: 4210, impressions: 42300, clicks: 804, ctr: 1.9, frequency: 2.2, results: 16, revenue: 18400 },
    { id: "ad-1b", organizationId: "org-casa-norte", campaignId: "cmp-1", adSetId: "as-1", name: "Otoño · Detalle madera", status: "ACTIVE", spend: 3890, impressions: 38100, clicks: 305, ctr: 0.8, frequency: 4.6, results: 7, revenue: 7300 },
    { id: "ad-1c", organizationId: "org-casa-norte", campaignId: "cmp-1", adSetId: "as-1", name: "Otoño · Envío gratis", status: "ACTIVE", spend: 3120, impressions: 29800, clicks: 507, ctr: 1.7, frequency: 1.9, results: 12, revenue: 13900 },
    { id: "ad-2a", organizationId: "org-casa-norte", campaignId: "cmp-2", adSetId: "as-2", name: "Remarketing · Carrito", status: "ACTIVE", spend: 5480, impressions: 21900, clicks: 613, ctr: 2.8, frequency: 3.1, results: 23, revenue: 22400 },
    { id: "ad-3a", organizationId: "org-casa-norte", campaignId: "cmp-3", adSetId: "as-3", name: "Catálogo dinámico", status: "ACTIVE", spend: 3610, impressions: 33200, clicks: 431, ctr: 1.3, frequency: 2.7, results: 12, revenue: 9400 },
    { id: "ad-5a", organizationId: "org-brava", campaignId: "cmp-5", adSetId: "as-5", name: "Lead Gen · Testimonio", status: "ACTIVE", spend: 3540, impressions: 30400, clicks: 669, ctr: 2.2, frequency: 2.4, results: 31, revenue: 26350 },
    { id: "ad-5b", organizationId: "org-brava", campaignId: "cmp-5", adSetId: "as-5", name: "Lead Gen · Oferta genérica", status: "ACTIVE", spend: 1960, impressions: 17800, clicks: 142, ctr: 0.8, frequency: 2.1, results: 0, revenue: 0 },
    { id: "ad-6a", organizationId: "org-lumbre", campaignId: "cmp-6", adSetId: "as-6", name: "Mensajes · Latte de temporada", status: "ACTIVE", spend: 2210, impressions: 26400, clicks: 739, ctr: 2.8, frequency: 2.6, results: 54, revenue: 16740 },
  ],
  actions: [],
  budgetChanges: [],
  metrics: {
    "org-casa-norte": [
      { date: "21 Ago", spend: 2190, revenue: 6410, roas: 2.93 },
      { date: "23 Ago", spend: 2740, revenue: 9220, roas: 3.36 },
      { date: "25 Ago", spend: 3010, revenue: 8880, roas: 2.95 },
      { date: "27 Ago", spend: 3380, revenue: 11940, roas: 3.53 },
      { date: "29 Ago", spend: 3650, revenue: 14120, roas: 3.87 },
      { date: "31 Ago", spend: 4010, revenue: 13290, roas: 3.31 },
      { date: "02 Sep", spend: 4230, revenue: 16940, roas: 4.0 },
      { date: "03 Sep", spend: 4480, revenue: 17620, roas: 3.93 },
    ],
    "org-brava": [
      { date: "21 Ago", spend: 1120, revenue: 2840, roas: 2.54 }, { date: "23 Ago", spend: 1240, revenue: 3560, roas: 2.87 },
      { date: "25 Ago", spend: 1380, revenue: 4290, roas: 3.11 }, { date: "27 Ago", spend: 1510, revenue: 4730, roas: 3.13 },
      { date: "29 Ago", spend: 1460, revenue: 5120, roas: 3.51 }, { date: "31 Ago", spend: 1640, revenue: 5480, roas: 3.34 },
      { date: "02 Sep", spend: 1720, revenue: 6110, roas: 3.55 }, { date: "03 Sep", spend: 1800, revenue: 6480, roas: 3.6 },
    ],
    "org-lumbre": [
      { date: "21 Ago", spend: 610, revenue: 1390, roas: 2.28 }, { date: "23 Ago", spend: 720, revenue: 1580, roas: 2.19 },
      { date: "25 Ago", spend: 680, revenue: 1780, roas: 2.62 }, { date: "27 Ago", spend: 740, revenue: 1890, roas: 2.55 },
      { date: "29 Ago", spend: 790, revenue: 2100, roas: 2.66 }, { date: "31 Ago", spend: 840, revenue: 2240, roas: 2.67 },
      { date: "02 Sep", spend: 920, revenue: 2380, roas: 2.59 }, { date: "03 Sep", spend: 970, revenue: 2460, roas: 2.54 },
    ],
  },
  activities: [
    { id: "act-1", organizationId: "org-casa-norte", agent: "Presupuesto", title: "Redistribuí $280 diarios", detail: "Moví presupuesto de Advantage+ a Remarketing por una diferencia de ROAS de 1.51×.", impact: "+$1,940 estimados/mes", kind: "action", createdAt: "Hace 18 min" },
    { id: "act-2", organizationId: "org-casa-norte", agent: "Audiencias", title: "Detecté fatiga en 25–34", detail: "La frecuencia subió a 4.2 y el CTR cayó 17%. Preparé una audiencia amplia alternativa.", impact: "Prueba iniciada", kind: "warning", createdAt: "Hace 46 min" },
    { id: "act-3", organizationId: "org-casa-norte", agent: "Creativos", title: "Generé 3 variantes", detail: "Nuevos titulares basados en el ángulo ganador: entrega gratis y materiales durables.", impact: "En aprendizaje", kind: "action", createdAt: "Hace 2 h" },
    { id: "act-4", organizationId: "org-casa-norte", agent: "Analista", title: "El ROAS semanal mejoró", detail: "El retorno pasó de 3.12× a 3.49× manteniendo estable el costo por compra.", impact: "+11.9% ROAS", kind: "insight", createdAt: "Hace 4 h" },
    { id: "act-5", organizationId: "org-brava", agent: "Estratega", title: "Recomendación lista", detail: "Conviene ampliar el público similar de 1% a 3%.", impact: "+18% alcance potencial", kind: "insight", createdAt: "Hace 1 h" },
  ],
  alerts: [
    { id: "al-1", organizationId: "org-casa-norte", severity: "warning", title: "Fatiga creativa detectada", detail: "Advantage+ · Catálogo perdió 21% de CTR en los últimos 5 días.", createdAt: "Hace 46 min", read: false },
    { id: "al-2", organizationId: "org-casa-norte", severity: "success", title: "Meta de ROAS superada", detail: "Remarketing mantiene 4.12×, por encima de la meta de 3.5×.", createdAt: "Hace 2 h", read: false },
    { id: "al-3", organizationId: "org-casa-norte", severity: "info", title: "Sincronización completada", detail: "Campañas, anuncios y métricas están al día.", createdAt: "Hace 12 min", read: true },
    { id: "al-4", organizationId: "org-brava", severity: "warning", title: "Recomendación pendiente", detail: "Hay un cambio de audiencia esperando tu aprobación.", createdAt: "Hace 1 h", read: false },
  ],
  creatives: [
    { id: "cr-1", organizationId: "org-casa-norte", title: "Hogar que se siente tuyo", headline: "Diseño que dura. Envío gratis.", primaryText: "Transforma tu espacio con piezas hechas para acompañarte todos los días.", status: "Ganador", format: "Imagen", score: 94, palette: ["#d7c4a8", "#6f8068", "#f3ede2"] },
    { id: "cr-2", organizationId: "org-casa-norte", title: "Colección nueva", headline: "Tu casa, en su mejor versión", primaryText: "Conoce la colección Otoño. Materiales nobles, diseño atemporal y entrega nacional.", status: "Probando", format: "Carrusel", score: 87, palette: ["#342f2b", "#c9754b", "#e9d9c7"] },
    { id: "cr-3", organizationId: "org-casa-norte", title: "Testimonio visual", headline: "Más de 2,000 hogares renovados", primaryText: "Mira cómo una sola pieza puede cambiar por completo tu espacio.", status: "Borrador", format: "Video", score: 82, palette: ["#233342", "#d5a45d", "#f6f4ef"] },
  ],
};
